SchemeUserState.Snake_.scheme.orderHint=0
SchemeUserState.Snake_.scheme.shared=true

scheme.Snake_.name=Snake_
scheme.Snake_.mainClass=App
scheme.Snake_.workingDirectory=Snake_
scheme.Snake_.programArguments=
scheme.Snake_.vmOptions=
